Audrey/checkbox
StanfordSpezi/spezi-web-design-system pull request #27
Opened 2024-12-15 05:04 UTC by ivyalin2015

# *Name of the PR*

## :recycle: Current situation & Problem
[Add Radio input component](https://github.com/StanfordSpezi/spezi-web-design-system/issues/16)

## :gear: Release Notes 
- Allows users to select one option from a dropdown list with as many items as desired
- Uses standardized coloring

## :books: Documentation
*Please ensure that you properly document any additions in conformance to [Spezi Documentation Guide](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md).*

This RadioInput component provides a template to create a multiple choice question. 
<img width="157" alt="image" src="https://github.com/user-attachments/assets/4a6a238b-ad23-4091-b21b-8fb563b32265" />

## :white_check_mark: Testing
*Please ensure that the PR meets the testing requirements set by CodeCov and that new functionality is appropriately tested.*
My tests mainly focus on rendering but do not include confirmation that different items can be selected.

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [ v ] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

2025-01-06 20:36 UTC, arkadiuszbachorski requested changes

2025-01-06 20:36 UTC, arkadiuszbachorski commented on package.json
> +    "build-storybook": "storybook build"
We don't need `build-storybook` command.

2025-01-06 20:36 UTC, arkadiuszbachorski commented on package.json
> +    "@chromatic-com/storybook": "^3.2.2",
Why are storybook version changed and new dependencies added? It looks like you might have accidentally reinstall Storybook, as there is a `@chromatic-com/storybook` dep that I keep removing on every fresh Storybook installation. 

Could you please revert that?

2025-01-06 20:36 UTC, arkadiuszbachorski commented on src/components/Checkbox/Checkbox.stories.tsx
> +//
Could you please remove `Checkbox` elements from this PR? Let's keep this PR scoped to `Radio`.

2025-01-06 20:36 UTC, arkadiuszbachorski commented on src/RadioInput/RadioInput.stories.tsx
> +    className="RadioGroupRoot flex flex-col space-y-4"
What is `RadioGroupRoot` class here for?

2025-01-06 20:36 UTC, arkadiuszbachorski commented on src/RadioInput/RadioInput.stories.tsx
> +    <div className="flex items-center space-x-2">
This is a bit too complex to be repeated each time. I'd love to have `SideLabel` component that renders correct `input + label` element for both Checkbox and Radio. 

I imagine such usage:


```
<SideLabel label="Second choice">
  <Radio value="2" />
</SideLabel>
```

If `<label>` contains `input`, there is no need for `htmlFor` and `id`, it's implicit!

2025-01-06 20:36 UTC, arkadiuszbachorski commented on src/RadioInput/RadioInput.stories.tsx
> +  <RadioInput
We should have a component that renders group of radios already styled. I.e. we want to make sure common need of rendering multiple radios does not need any additional styling.

2025-01-06 20:36 UTC, arkadiuszbachorski commented on src/RadioInput/RadioInput.tsx
Could we rename this to `Radio`? Just to keep it consistent with `Checkbox` name.

2025-01-06 20:36 UTC, arkadiuszbachorski commented on src/RadioInput/RadioInput.tsx
> +        'relative flex h-6 w-6 items-center justify-center rounded-full border-2 border-border focus:ring-2 focus:ring-ring focus:ring-offset-1',
We have `flex-center` class that is a shorthand for `flex items-center justify-center`. Extremely often used.

`h-6 w-6` can be represented as `size-6`. It's worth to indicate that both dimensions are meant to be the same.

We have `focus-ring` class for focus properties. It should do the trick as well here.

2025-01-06 20:36 UTC, arkadiuszbachorski commented on src/RadioInput/RadioInput.tsx
> +    )}
Let's keep `label` separate from the Radio item itself. By relying on composition through other elements, it makes it easier to build reusable components. Labels can quite often require customization, so it's better just to keep it as separate component, using elements like `SideLabel` (mentioned in other comment)

2025-01-06 20:36 UTC, arkadiuszbachorski commented on src/RadioInput/RadioInput.tsx
> +export const RadioIndicator = forwardRef<
Every `RadioItem` is always going to have Indicator. Could we just put the indicator inside the `RadioItem`? If someone needs something custom on this matter, they usually are going to opt-out from this component anyway. 

What I value here is simplicity of usage.

2025-01-06 20:37 UTC, arkadiuszbachorski commented
@ivyalin2015 Thank you for working on this! I left couple comments, could you please address them?

2025-01-14 07:03 UTC, arkadiuszbachorski commented on src/RadioInput/RadioInput.stories.tsx
> +    <div className="flex items-center space-x-2">
Just a note, we already have `SideLabel` component.

2025-01-14 23:20 UTC, ivyalin2015 commented on src/RadioInput/RadioInput.stories.tsx
> +    className="RadioGroupRoot flex flex-col space-y-4"
That might have been from earlier iterations - just removed!

2025-01-15 00:07 UTC, ivyalin2015 commented on src/RadioInput/RadioInput.tsx
> +        'relative flex h-6 w-6 items-center justify-center rounded-full border-2 border-border focus:ring-2 focus:ring-ring focus:ring-offset-1',
Hmm... I was having an issue of the focus-ring disappearing when I used `focus-ring`, like this: 

<img width="162" alt="image" src="https://github.com/user-attachments/assets/38ffeee8-fec7-4d01-9875-14d3286c5862" />

Just to make sure, should the tailwind code look something like this?
`className={cn(
        'relative flex-center size-6 rounded-full border-2 border-secondary focus-ring',
        className,
      )}`

2025-01-15 20:45 UTC, arkadiuszbachorski requested changes
We also need `index.tsx` file in the `Radio` directory that exports `Radio` components. This is necessary, because we want `components/Radio` to be a module itself. 

Furthermore, we need Checkbox to be exported from `src/index.tsx` (to make it accessible from `@stanfordspezi/spezi-web-design-system` module) and from `package.json` (to make it accessible as `@stanfordspezi/spezi-web-design-system/components/Radio`). 

Referencing this PR should help: https://github.com/StanfordSpezi/spezi-web-design-system/pull/36/files

2025-01-15 20:45 UTC, arkadiuszbachorski commented on package.json
> +    "@radix-ui/react-icons": "^1.3.2",
We don't need these dependencies.

2025-01-15 20:45 UTC, arkadiuszbachorski commented on src/components/Radio/Radio.tsx
> +    {label && <SideLabel className="popover-foreground">{label}</SideLabel>}
As I clarified on Slack, `label` should be removed from this component.

2025-01-15 21:06 UTC, arkadiuszbachorski commented on src/RadioInput/RadioInput.tsx
> +        'relative flex h-6 w-6 items-center justify-center rounded-full border-2 border-border focus:ring-2 focus:ring-ring focus:ring-offset-1',
This is would be an ideal implementation of Radio with indicator and styles. 

```
export const Radio = forwardRef<
  ElementRef<typeof RadioPrimitive.Item>,
  ComponentPropsWithoutRef<typeof RadioPrimitive.Item>
>(({ className, ...props }, ref) => (
  <RadioPrimitive.Item
    ref={ref}
    className={cn(
      'focus-ring flex-center size-4 shrink-0 rounded-full border border-input disabled:cursor-not-allowed disabled:opacity-50',
      className,
    )}
    {...props}
  >
    <RadioPrimitive.Indicator className="flex-center size-2.5 rounded-full bg-primary" />
  </RadioPrimitive.Item>
))
Radio.displayName = RadioPrimitive.Item.displayName
```

Main aspects:
* focus is functional due to `focus-ring`
* size is exactly the same as `Checkbox`, but it's round, keeping the UI consistent and easy to match up together
* disabled state is handled

2025-01-29 03:18 UTC, ivyalin2015 commented
Ready for another check! I had to modify one of the formatting features in SideLabel for this request. SideLabel.stories.tsx might need some styling edits for the Storybook so that the text and switch are centered.

2025-01-29 21:27 UTC, arkadiuszbachorski requested changes
Thank you for iterating on this. We're almost there!

2025-01-29 21:27 UTC, arkadiuszbachorski commented on src/components/Radio/Radio.stories.tsx
> +  title: 'Components/RadioInput',
```suggestion
  title: 'Components/Radio',
```

2025-01-29 21:27 UTC, arkadiuszbachorski commented on src/components/SideLabel/SideLabel.tsx
> -    <div className="mt-1">{children}</div>
This change should not be necessary, because it has been already made with https://github.com/StanfordSpezi/spezi-web-design-system/pull/35.

Please merge `main` to your branch.

2025-01-29 21:27 UTC, arkadiuszbachorski commented on src/components/Radio/Radio.tsx
> +))
We need to do something about it. We can have `RadioIndicator` component, but it should be exactly the same as `Radio` uses and `Radio` should use it then. I don't think it's necessary, but I don't think it's harmful either, leaving it up to you!

2025-01-29 21:27 UTC, arkadiuszbachorski commented on src/components/Radio/Radio.tsx
> +// wrapper for one of the list items - includes selection circle and text
I find this comment misleading.

* `Radio` is not a wrapper, it's not supposed to wrap anything
* It doesn't contain any text
* selection circle is self-explanatory as concept of the "Radio UI element" is. I mean, every radio has some kind of selection indicator, it's already in the definition. 

What do you think of removing it? No comment seems enough, as regular `input type="radio"` does exactly the same thing.

2025-01-29 21:27 UTC, arkadiuszbachorski commented on src/components/Radio/Radio.tsx
> +// entire list of choices
These kind of comments should be using JSDoc notation. 

```suggestion
/**
 * entire list of choices
 * */
```

JSDoc allows writing documentation, it's a standard widely used. Editors rely on it to display hints in your IDE. Probably they'd work with regular comment as well, but let's keep it as JSDoc format.

Example JSDoc usage: [explaining maxToDisplay property of Breadcrumbs](https://github.com/StanfordBDHG/speziwebdesignsystem/blob/0fed267b7d111bd5d8616a0a00e8067c09094717/src/components/Breadcrumb/Breadcrumb.tsx#L165-L170)

2025-01-29 21:27 UTC, arkadiuszbachorski commented on src/components/Radio/Radio.tsx
> +// entire list of choices
When it comes to the content of this comment what do you think about something like `Container for Radio inputs`?

2025-01-29 21:27 UTC, arkadiuszbachorski commented on src/components/Radio/Radio.test.tsx
> +describe('RadioInput', () => {
```suggestion
describe('Radio', () => {
```

2025-01-29 21:27 UTC, arkadiuszbachorski commented on src/components/Radio/Radio.test.tsx
> +  it('renders radio buttons', () => {
```suggestion
  it('renders radio inputs', () => {
```

2025-01-29 21:27 UTC, arkadiuszbachorski commented on src/components/Radio/Radio.test.tsx
> +  })
Could we add a test whether change event works? See how it's done in checkbox for reference: 

https://github.com/StanfordSpezi/spezi-web-design-system/blob/0efe4ad9765272b212ade5734451eef91cd387f5/src/components/Checkbox/Checkbox.test.tsx#L26-L28


Essentially, we want to be sure that radio is functional.

2025-01-29 21:27 UTC, arkadiuszbachorski commented on src/components/Radio/Radio.stories.tsx
> +export const Default = () => (
We definitely do not want to add any classNames for just basic usage of radios. I mean, `RadioGroup` should have some spacing already built-in, `SideLabel` should work out of the box and `Radio` as well. No `className` should be provided anywhere in this `Default` story, to render a functional Radio. That's our goal - we want elements to be ready and easy to use, with very little configuration, styling and modifications necessary.

2025-01-29 21:27 UTC, arkadiuszbachorski commented on src/components/Radio/Radio.stories.tsx
> +    <SideLabel htmlFor="r1" label="Default" className="flex items-center">
`htmlFor` is not necessary. `SideLabel` (HTML `label`) wraps Radio (HTML `input type="radio"`), which ties them together without `htmlFor`. 

You can test it easily in the browser.

```
<label>
  Example
  <input type="checkbox">
</label>
```

Clicking on "Example" text checks checkbox.

2025-01-29 21:27 UTC, arkadiuszbachorski commented on package.json
>      "@radix-ui/react-checkbox": "^1.1.2",
Unwanted dependencies are still there.

Could you please make sure that there is no changes to `.gitignore`, `package.json` nor `package-lock.json`?

2025-02-01 19:21 UTC, ivyalin2015 commented on src/components/Radio/Radio.tsx
> +// wrapper for one of the list items - includes selection circle and text
That makes sense! I originally put it there while I was working to keep track of the different components, but I removed it now :)

2025-02-01 19:26 UTC, ivyalin2015 commented on src/components/Radio/Radio.stories.tsx
> +export const Default = () => (
Removed the classNames! I still don't see the green focus ring when I select the elements though, even though it's in the classname in Radio.tsx

2025-02-01 19:27 UTC, ivyalin2015 commented on src/components/Radio/Radio.stories.tsx
> +    <SideLabel htmlFor="r1" label="Default" className="flex items-center">
Removed!

2025-02-02 09:18 UTC, arkadiuszbachorski requested changes
There are still conflicts in this branch. Please merge `StanfordSpezi:main` into your branch, using `git merge`. 

Afterwards, please make sure that `Radio` is exposed in the `package.json` in the `exports`.

That should be the last steps! :)

2025-02-02 09:18 UTC, arkadiuszbachorski commented on src/components/Radio/Radio.stories.tsx
> +    className="flex flex-col space-y-4"
There is still a `className` here

2025-02-02 09:18 UTC, arkadiuszbachorski commented on src/components/Radio/Radio.test.tsx
> +    expect(option1).not.toBeChecked()
Good job! 🚀

2025-02-23 21:43 UTC, arkadiuszbachorski requested changes
Last polishes!

2025-02-23 21:43 UTC, arkadiuszbachorski commented on package.json
> +}
Let's keep new-line at the end of the file.

2025-02-23 21:43 UTC, arkadiuszbachorski commented on .gitignore
> +.idea/
Let's keep new-line at the end of the file.

2025-02-23 21:43 UTC, arkadiuszbachorski commented on package-lock.json
There should be no changes to `package-lock`. Nothing new has been installed/updated in this PR, therefore `package-lock` should stay as is. Can you please revert this change? Let me know if some changes automatically re-appear whenever you install the dependencies, but that should not be the case.

2025-02-23 21:50 UTC, arkadiuszbachorski commented
@ivyalin2015 ESLint fails. Could you please make sure that `npm run prepush` returns no errors locally for you?

2025-03-02 04:56 UTC, ivyalin2015 commented on package-lock.json
I used git restore this time to pull the version from main - let me know if that is still an issue!

2025-03-10 08:22 UTC, arkadiuszbachorski requested changes
Last bit

2025-03-10 08:22 UTC, arkadiuszbachorski commented on package.json
> +    "eslint": "^9.21.0",
This change should not be present here

2025-03-10 08:22 UTC, arkadiuszbachorski commented on package.json
> +    "prettier": "^3.5.2",
This change should not be present here

2025-03-10 08:57 UTC, arkadiuszbachorski requested changes

2025-03-10 08:57 UTC, arkadiuszbachorski commented on package.json
> +    "@stanfordspezi/spezi-web-configurations": "^0.2.1",
This one as well actually. It would be fine, but let's keep as is for sake of this PR. I'll handle update in a separate PR.

2025-03-10 08:57 UTC, arkadiuszbachorski commented on package.json
> +    "@stanfordspezi/spezi-web-configurations": "^0.2.1",
```suggestion
    "@stanfordspezi/spezi-web-configurations": "^0.2.0",
```

2025-03-10 14:53 UTC, arkadiuszbachorski commented
@ivyalin2015 It looks like there is some flaky/failing test. It doesn't seem to be related with your PR, don't worry about it. I'll verify and fix if necessary.

2025-03-11 01:41 UTC, ivyalin2015 commented
I was seeing a ESLint error even though it passes `npm run prepush` before but that disappeared on my end - just thought I should let you know in case it's consistent with the error you're seeing!

2025-03-13 18:25 UTC, arkadiuszbachorski approved these changes

2025-03-13 18:26 UTC, merged